# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ExperiencesModal`.
# Please instead update this file by running `bin/tapioca dsl ExperiencesModal`.


class ExperiencesModal
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
