# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::CheckboxFieldComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::CheckboxFieldComponent`.


class Ui::CheckboxFieldComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
