# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::DateInputComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::DateInputComponent`.


class Ui::DateInputComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
