# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::InputFieldComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::InputFieldComponent`.


class Ui::InputFieldComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
