# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::MultiSelect2Component`.
# Please instead update this file by running `bin/tapioca dsl Ui::MultiSelect2Component`.


class Ui::MultiSelect2Component
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
