# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::MultiselectComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::MultiselectComponent`.


class Ui::MultiselectComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
