# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::MultiSelectFieldComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::MultiSelectFieldComponent`.


class Ui::MultiSelectFieldComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
