# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::NumberInputComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::NumberInputComponent`.


class Ui::NumberInputComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
