# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::SelectFieldComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::SelectFieldComponent`.


class Ui::SelectFieldComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
