# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::StringInputComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::StringInputComponent`.


class Ui::StringInputComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
