# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Ui::TextAreaComponent`.
# Please instead update this file by running `bin/tapioca dsl Ui::TextAreaComponent`.


class Ui::TextAreaComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
