# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Form::InputComponent`.
# Please instead update this file by running `bin/tapioca dsl Form::InputComponent`.


class Form::InputComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
